# Generated by Django 2.1.4 on 2020-04-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='age',
            field=models.PositiveIntegerField(null=True, verbose_name='Возраст'),
        ),
    ]
