# Generated by Django 2.1.4 on 2020-03-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomprofile',
            name='img_path',
            field=models.CharField(blank=True, max_length=128, verbose_name='Путь к изображению'),
        ),
    ]
