# Generated by Django 2.1.4 on 2020-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_roomprofile_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='img_path',
            field=models.ImageField(upload_to='pict'),
        ),
    ]
