# Generated by Django 2.1.4 on 2020-04-06 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20200406_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingprofile',
            name='day',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
