# Generated by Django 2.1.4 on 2020-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20200428_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomprofile',
            name='img_path',
            field=models.ImageField(upload_to='assets'),
        ),
    ]
